linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - asciicheck
    - bodyclose
    - dogsled
    - exhaustive
    - exportloopref
    - gocognit
    - goconst
    - goheader
    - gosec
    - misspell
    - nakedret
    - nestif
    - unconvert
    - unparam
    - whitespace
    - prealloc
    - execinquery

issues:
  exclude:
    - "composite literal uses unkeyed fields"
    - "composites: go.mongodb.org/mongo-driver/bson/primitive.E struct literal uses unkeyed fields"
    - "Potential HTTP request made with variable url"
    - G404
    - G501
    - G401
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - noctx
        - unparam
        - bodyclose
    - path: fixtures.go
      linters:
        - gosec
